name: bottegeppetto
region: nyc3

services:
- name: bottegeppetto
  git:
    branch: main
    repo_clone_url: https://github.com/mchatman/bottegeppetto.git
  run_command: ./bottegeppetto
  dockerfile_path: Dockerfile
  instance_count: 1
  instance_size_slug: basic-xs
  http_port: 8080

  envs:
  - key: PORT
    value: "8080"